=== Chklang/pokemonGoDB/data/attacks.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	
	<xsd:element name="attacks" type="Attacks" />
	
	<xsd:complexType name="Attacks">
		<xsd:sequence>
			<xsd:element name="attack" type="Attack" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="Attack">
		<xsd:attribute name="id" type="xsd:int" use="required" />
		<xsd:attribute name="power" type="xsd:int" use="required" />
		<xsd:attribute name="energy" type="xsd:int" use="required" />
		<xsd:attribute name="damage_duration" type="xsd:int" use="required" />
		<xsd:attribute name="damage_start" type="xsd:int" use="required" />
		<xsd:attribute name="damage_end" type="xsd:int" use="required" />
		<xsd:attribute name="typePokemon" type="xsd:int" use="required" />
		<xsd:attribute name="accurancy" type="xsd:int" use="required" />
		<xsd:attribute name="critical" type="xsd:double" use="required" />
		<xsd:attribute name="typeAttack" type="xsd:string" use="required" />
	</xsd:complexType>

</xsd:schema>

=== Chklang/pokemonGoDB/data/attacks.xml
<?xml version="1.0" encoding="utf-8"?>
<attacks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="attacks.xsd">
	<attack id="1" power="25" energy="5" damage_duration="4000" damage_start="2800" damage_end="3400" typePokemon="1" accurancy="1" critical="0.05000000074505806" typeAttack="special" />
	<attack id="2" power="120" energy="1" damage_duration="5000" damage_start="4000" damage_end="4800" typePokemon="1" accurancy="1" critical="0.05000000074505806" typeAttack="special" />
	<attack id="3" power="45" energy="3" damage_duration="3500" damage_start="2300" damage_end="3400" typePokemon="17" accurancy="1" critical="0.05000000074505806" typeAttack="special" />
	<attack id="4" power="30" energy="4" damage_duration="2600" damage_start="1850" damage_end="2350" typePokemon="4" accurancy="1" critical="0.05000000074505806" typeAttack="special" />
	<attack id="5" power="25" energy="5" damage_duration="2100" damage_start="1850" damage_end="2100" typePokemon="1" accurancy="1" critical="0.05000000074505806" typeAttack="special" />
	<attack id="6" power="40" energy="4" damage_duration="4600" damage_start="2700" damage_end="3200" typePokemon="10" accurancy="1" critical="0.05000000074505806" typeAttack="special" />
	<attack id="7" power="80" energy="1" damage_duration="3200" damage_start="2400" damage_end="2700" typePokemon="7" accurancy="1" critical="0.05000000074505806" typeAttack="special" />
	<attack id="8" power="55" energy="2" damage_duration="2900" damage_start="1700" damage_end="2600" typePokemon="10" accurancy="1" critical="0.05000000074505806" typeAttack="special" />
	<attack id="9" power="70" energy="3" damage_duration="5800" damage_start="4600" damage_end="5000" typePokemon="5" accurancy="1" critical="0.05000000074505806" typeAttack="special" />
	<attack id="10" power="60" energy="1" damage_duration="2000" damage_start="1500" damage_end="1800" typePokemon="2" accurancy="1" critical="0.25" typeAttack="special" />
	<attack id="11" power="40" energy="4" damage_duration="3800" damage_start="2300" damage_end="3600" typePokemon="14" accurancy="1" critical="0.05000000074505806" typeAttack="special" />
	<attack id="12" power="100" energy="1" damage_duration="4200" damage_start="2000" damage_end="3950" typePokemon="5" accurancy="1" critical="0.05000000074505806" typeAttack="special" />
	<attack id="13" power="80" energy="1" damage_duration="3100" damage_start="1400" damage_end="1800" typePokemon="6" accurancy="1" critical="0.5" typeAttack="special" />
	<attack id="14" power="45" energy="3" damage_duration="3500" damage_start="2100" damage_end="3200" typePokemon="15" accurancy="1" critical="0.05000000074505806" typeAttack="special" />
	<attack id="15" power="25" energy="4" damage_duration="2550" damage_start="1950" damage_end="2250" typePokemon="14" accurancy="1" critical="0.05000000074505806" typeAttack="special" />
	<attack id="16" power="35" energy="3" damage_duration="2500" damage_start="1600" damage_end="2300" typePokemon="13" accurancy="1" critical="0.05000000074505806" typeAttack="special" />
	<attack id="17" power="60" energy="3" damage_duration="3900" damage_start="2400" damage_end="3500" typePokemon="9" accurancy="1" critical="0.05000000074505806" typeAttack="special" />
	<attack id="18" power="40" energy="3" damage_duration="2700" damage_start="1600" damage_end="2500" typePokemon="3" accurancy="1" critical="0.05000000074505806" typeAttack="special" />
	<attack id="19" power="65" energy="2" damage_duration="3650" damage_start="2150" damage_end="3500" typePokemon="15" accurancy="1" critical="0.05000000074505806" typeAttack="special" />
	<attack id="20" power="100" energy="1" damage_duration="3900" damage_start="3600" damage_end="3600" typePokemon="15" accurancy="1" critical="0.05000000074505806" typeAttack="special" />
	<attack id="21" power="80" energy="1" damage_duration="3800" damage_start="3000" damage_end="3400" typePokemon="10" accurancy="1" critical="0.05000000074505806" typeAttack="special" />
	<attack id="22" power="30" energy="4" damage_duration="2900" damage_start="2000" damage_end="2600" typePokemon="3" accurancy="1" critical="0.05000000074505806" typeAttack="special" />
	<attack id="23" power="50" energy="3" damage_duration="3400" damage_start="2100" damage_end="2800" typePokemon="5" accurancy="1" critical="0.25" typeAttack="special" />
	<attack id="24" power="65" energy="2" damage_duration="3200" damage_start="2100" damage_end="3100" typePokemon="12" accurancy="1" critical="0.05000000074505806" typeAttack="special" />
	<attack id="25" power="25" energy="5" damage_duration="3200" damage_start="1400" damage_end="2600" typePokemon="12" accurancy="1" critical="0.05000000074505806" typeAttack="special" />
	<attack id="26" power="75" energy="2" damage_duration="4250" damage_start="2600" damage_end="4100" typePokemon="7" accurancy="1" critical="0.05000000074505806" typeAttack="special" />
	<attack id="27" power="25" energy="5" damage_duration="2400" damage_start="1650" damage_end="1850" typePokemon="4" accurancy="1" critical="0.05000000074505806" typeAttack="special" />
	<attack id="28" power="30" energy="4" damage_duration="2700" damage_start="2400" damage_end="2600" typePokemon="17" accurancy="1" critical="0.25" typeAttack="special" />
	<attack id="29" power="30" energy="4" damage_duration="2900" damage_start="2600" damage_end="2800" typePokemon="11" accurancy="1" critical="0.05000000074505806" typeAttack="special" />
	<attack id="30" power="30" energy="3" damage_duration="2100" damage_start="1850" damage_end="2000" typePokemon="2" accurancy="1" critical="0.05000000074505806" typeAttack="special" />
	<attack id="31" power="30" energy="4" damage_duration="2250" damage_start="2000" damage_end="2150" typePokemon="2" accurancy="1" critical="0.05000000074505806" typeAttack="special" />
	<attack id="32" power="25" energy="5" damage_duration="2350" damage_start="1700" damage_end="2100" typePokemon="11" accurancy="1" critical="0.05000000074505806" typeAttack="special" />
	<attack id="33" power="45" energy="2" damage_duration="2350" damage_start="2050" damage_end="2250" typePokemon="11" accurancy="1" critical="0.05000000074505806" typeAttack="special" />
	<attack id="34" power="40" energy="3" damage_duration="2400" damage_start="1300" damage_end="1800" typePokemon="12" accurancy="1" critical="0.05000000074505806" typeAttack="special" />
	<attack id="35" power="40" energy="3" damage_duration="2700" damage_start="2200" damage_end="2700" typePokemon="14" accurancy="1" critical="0.05000000074505806" typeAttack="special" />
	<attack id="36" power="35" energy="4" damage_duration="3600" damage_start="2900" damage_end="3250" typePokemon="6" accurancy="1" critical="0.05000000074505806" typeAttack="special" />
	<attack id="37" power="30" energy="4" damage_duration="3400" damage_start="2300" damage_end="3200" typePokemon="6" accurancy="1" critical="0.25" typeAttack="special" />
	<attack id="38" power="50" energy="3" damage_duration="3200" damage_start="1500" damage_end="2900" typePokemon="6" accurancy="1" critical="0.05000000074505806" typeAttack="special" />
	<attack id="39" power="40" energy="3" damage_duration="2900" damage_start="2000" damage_end="2800" typePokemon="6" accurancy="1" critical="0.05000000074505806" typeAttack="special" />
	<attack id="40" power="25" energy="5" damage_duration="3100" damage_start="2300" damage_end="2900" typePokemon="8" accurancy="1" critical="0.05000000074505806" typeAttack="special" />
	<attack id="41" power="25" energy="4" damage_duration="2100" damage_start="1400" damage_end="1700" typePokemon="8" accurancy="1" critical="0.05000000074505806" typeAttack="special" />
	<attack id="42" power="30" energy="4" damage_duration="3100" damage_start="1850" damage_end="2100" typePokemon="8" accurancy="1" critical="0.05000000074505806" typeAttack="special" />
	<attack id="43" power="45" energy="3" damage_duration="3080" damage_start="2300" damage_end="2600" typePokemon="8" accurancy="1" critical="0.05000000074505806" typeAttack="special" />
	<attack id="44" power="30" energy="4" damage_duration="2800" damage_start="1750" damage_end="2300" typePokemon="9" accurancy="1" critical="0.05000000074505806" typeAttack="special" />
	<attack id="45" power="30" energy="3" damage_duration="2000" damage_start="1550" damage_end="1800" typePokemon="9" accurancy="1" critical="0.05000000074505806" typeAttack="special" />
	<attack id="46" power="25" energy="5" damage_duration="2100" damage_start="1300" damage_end="1700" typePokemon="13" accurancy="1" critical="0.05000000074505806" typeAttack="special" />
	<attack id="47" power="40" energy="3" damage_duration="2400" damage_start="1950" damage_end="2200" typePokemon="13" accurancy="1" critical="0.05000000074505806" typeAttack="special" />
	<attack id="48" power="100" energy="1" damage_duration="4300" damage_start="2550" damage_end="4100" typePokemon="13" accurancy="1" critical="0.05000000074505806" typeAttack="special" />
	<attack id="49" power="55" energy="2" damage_duration="2700" damage_start="1900" damage_end="2700" typePokemon="13" accurancy="1" critical="0.05000000074505806" typeAttack="special" />
	<attack id="50" power="25" energy="5" damage_duration="2700" damage_start="850" damage_end="2600" typePokemon="16" accurancy="1" critical="0.05000000074505806" typeAttack="special" />
	<attack id="51" power="65" energy="2" damage_duration="3600" damage_start="2100" damage_end="3300" typePokemon="16" accurancy="1" critical="0.05000000074505806" typeAttack="special" />
	<attack id="52" power="35" energy="2" damage_duration="1500" damage_start="1200" damage_end="1400" typePokemon="16" accurancy="1" critical="0.25" typeAttack="special" />
	<attack id="53" power="25" energy="5" damage_duration="3900" damage_start="1800" damage_end="3600" typePokemon="18" accurancy="1" critical="0.05000000074505806" typeAttack="special" />
