=== Chklang/pokemonGoDB/data/lang-pokemons.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	
	<xsd:element name="pokemons" type="Pokemons" />
	
	<xsd:complexType name="Pokemons">
		<xsd:sequence>
			<xsd:element name="pokemon" type="Pokemon" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="Pokemon">
		<xsd:simpleContent>
			<xsd:extension base="xsd:string">
				<xsd:attribute name="id" type="xsd:int" use="required" />
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>

</xsd:schema>

=== Chklang/pokemonGoDB/data/lang-it/lang_pokemons.xml
<?xml version="1.0" encoding="utf-8"?>
<pokemons xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../lang-pokemons.xsd">
	<pokemon id="1">Bulbasaur</pokemon>
	<pokemon id="2">Ivysaur</pokemon>
	<pokemon id="3">Venusaur</pokemon>
	<pokemon id="4">Charmander</pokemon>
	<pokemon id="5">Charmeleon</pokemon>
	<pokemon id="6">Charizard</pokemon>
	<pokemon id="7">Squirtle</pokemon>
	<pokemon id="8">Wartortle</pokemon>
	<pokemon id="9">Blastoise</pokemon>
	<pokemon id="10">Caterpie</pokemon>
	<pokemon id="11">Metapod</pokemon>
	<pokemon id="12">Butterfree</pokemon>
	<pokemon id="13">Weedle</pokemon>
	<pokemon id="14">Kakuna</pokemon>
	<pokemon id="15">Beedrill</pokemon>
	<pokemon id="16">Pidgey</pokemon>
	<pokemon id="17">Pidgeotto</pokemon>
	<pokemon id="18">Pidgeot</pokemon>
	<pokemon id="19">Rattata</pokemon>
	<pokemon id="20">Raticate</pokemon>
	<pokemon id="21">Spearow</pokemon>
	<pokemon id="22">Fearow</pokemon>
	<pokemon id="23">Ekans</pokemon>
	<pokemon id="24">Arbok</pokemon>
	<pokemon id="25">Pikachu</pokemon>
	<pokemon id="26">Raichu</pokemon>
	<pokemon id="27">Sandshrew</pokemon>
	<pokemon id="28">Sandslash</pokemon>
	<pokemon id="29">Nidoran♀</pokemon>
	<pokemon id="30">Nidorina</pokemon>
	<pokemon id="31">Nidoqueen</pokemon>
	<pokemon id="32">Nidoran♂</pokemon>
	<pokemon id="33">Nidorino</pokemon>
	<pokemon id="34">Nidoking</pokemon>
	<pokemon id="35">Clefairy</pokemon>
	<pokemon id="36">Clefable</pokemon>
	<pokemon id="37">Vulpix</pokemon>
	<pokemon id="38">Ninetales</pokemon>
	<pokemon id="39">Jigglypuff</pokemon>
	<pokemon id="40">Wigglytuff</pokemon>
	<pokemon id="41">Zubat</pokemon>
	<pokemon id="42">Golbat</pokemon>
	<pokemon id="43">Oddish</pokemon>
	<pokemon id="44">Gloom</pokemon>
	<pokemon id="45">Vileplume</pokemon>
	<pokemon id="46">Paras</pokemon>
	<pokemon id="47">Parasect</pokemon>
	<pokemon id="48">Venonat</pokemon>
	<pokemon id="49">Venomoth</pokemon>
	<pokemon id="50">Diglett</pokemon>
	<pokemon id="51">Dugtrio</pokemon>
	<pokemon id="52">Meowth</pokemon>
	<pokemon id="53">Persian</pokemon>
	<pokemon id="54">Psyduck</pokemon>
	<pokemon id="55">Golduck</pokemon>
	<pokemon id="56">Mankey</pokemon>
	<pokemon id="57">Primeape</pokemon>
	<pokemon id="58">Growlithe</pokemon>
	<pokemon id="59">Arcanine</pokemon>
	<pokemon id="60">Poliwag</pokemon>
	<pokemon id="61">Poliwhirl</pokemon>
	<pokemon id="62">Poliwrath</pokemon>
	<pokemon id="63">Abra</pokemon>
	<pokemon id="64">Kadabra</pokemon>
	<pokemon id="65">Alakazam</pokemon>
	<pokemon id="66">Machop</pokemon>
	<pokemon id="67">Machoke</pokemon>
	<pokemon id="68">Machamp</pokemon>
	<pokemon id="69">Bellsprout</pokemon>
	<pokemon id="70">Weepinbell</pokemon>
	<pokemon id="71">Victreebel</pokemon>
	<pokemon id="72">Tentacool</pokemon>
	<pokemon id="73">Tentacruel</pokemon>
	<pokemon id="74">Geodude</pokemon>
	<pokemon id="75">Graveler</pokemon>
	<pokemon id="76">Golem</pokemon>
	<pokemon id="77">Ponyta</pokemon>
	<pokemon id="78">Rapidash</pokemon>
	<pokemon id="79">Slowpoke</pokemon>
	<pokemon id="80">Slowbro</pokemon>
	<pokemon id="81">Magnemite</pokemon>
	<pokemon id="82">Magneton</pokemon>
	<pokemon id="83">Farfetch\'d</pokemon>
	<pokemon id="84">Doduo</pokemon>
	<pokemon id="85">Dodrio</pokemon>
	<pokemon id="86">Seel</pokemon>
	<pokemon id="87">Dewgong</pokemon>
	<pokemon id="88">Grimer</pokemon>
	<pokemon id="89">Muk</pokemon>
	<pokemon id="90">Shellder</pokemon>
	<pokemon id="91">Cloyster</pokemon>
	<pokemon id="92">Gastly</pokemon>
	<pokemon id="93">Haunter</pokemon>
	<pokemon id="94">Gengar</pokemon>
	<pokemon id="95">Onix</pokemon>
	<pokemon id="96">Drowzee</pokemon>
	<pokemon id="97">Hypno</pokemon>
	<pokemon id="98">Krabby</pokemon>
	<pokemon id="99">Kingler</pokemon>
	<pokemon id="100">Voltorb</pokemon>
	<pokemon id="101">Electrode</pokemon>
	<pokemon id="102">Exeggcute</pokemon>
	<pokemon id="103">Exeggutor</pokemon>
	<pokemon id="104">Cubone</pokemon>
	<pokemon id="105">Marowak</pokemon>
	<pokemon id="106">Hitmonlee</pokemon>
	<pokemon id="107">Hitmonchan</pokemon>
	<pokemon id="108">Lickitung</pokemon>
	<pokemon id="109">Koffing</pokemon>
	<pokemon id="110">Weezing</pokemon>
	<pokemon id="111">Rhyhorn</pokemon>
	<pokemon id="112">Rhydon</pokemon>
	<pokemon id="113">Chansey</pokemon>
	<pokemon id="114">Tangela</pokemon>
	<pokemon id="115">Kangaskhan</pokemon>
	<pokemon id="116">Horsea</pokemon>
	<pokemon id="117">Seadra</pokemon>
	<pokemon id="118">Goldeen</pokemon>
	<pokemon id="119">Seaking</pokemon>
	<pokemon id="120">Staryu</pokemon>
	<pokemon id="121">Starmie</pokemon>
	<pokemon id="122">Mr. Mime</pokemon>
	<pokemon id="123">Scyther</pokemon>
	<pokemon id="124">Jynx</pokemon>
	<pokemon id="125">Electabuzz</pokemon>
	<pokemon id="126">Magmar</pokemon>
	<pokemon id="127">Pinsir</pokemon>
	<pokemon id="128">Tauros</pokemon>
	<pokemon id="129">Magikarp</pokemon>
	<pokemon id="130">Gyarados</pokemon>
	<pokemon id="131">Lapras</pokemon>
	<pokemon id="132">Ditto</pokemon>
	<pokemon id="133">Eevee</pokemon>
	<pokemon id="134">Vaporeon</pokemon>
	<pokemon id="135">Jolteon</pokemon>
	<pokemon id="136">Flareon</pokemon>
	<pokemon id="137">Porygon</pokemon>
	<pokemon id="138">Omanyte</pokemon>
	<pokemon id="139">Omastar</pokemon>
	<pokemon id="140">Kabuto</pokemon>
	<pokemon id="141">Kabutops</pokemon>
	<pokemon id="142">Aerodactyl</pokemon>
	<pokemon id="143">Snorlax</pokemon>
	<pokemon id="144">Articuno</pokemon>
	<pokemon id="145">Zapdos</pokemon>
	<pokemon id="146">Moltres</pokemon>
	<pokemon id="147">Dratini</pokemon>
	<pokemon id="148">Dragonair</pokemon>
	<pokemon id="149">Dragonite</pokemon>
	<pokemon id="150">Mewtwo</pokemon>
	<pokemon id="151">Mew</pokemon>
	<pokemon id="152">Chikorita</pokemon>
	<pokemon id="153">Bayleef</pokemon>
	<pokemon id="154">Meganium</pokemon>
	<pokemon id="155">Cyndaquil</pokemon>
	<pokemon id="156">Quilava</pokemon>
	<pokemon id="157">Typhlosion</pokemon>
	<pokemon id="158">Totodile</pokemon>
	<pokemon id="159">Croconaw</pokemon>
	<pokemon id="160">Feraligatr</pokemon>
	<pokemon id="161">Sentret</pokemon>
	<pokemon id="162">Furret</pokemon>
	<pokemon id="163">Hoothoot</pokemon>
	<pokemon id="164">Noctowl</pokemon>
	<pokemon id="165">Ledyba</pokemon>
	<pokemon id="166">Ledian</pokemon>
	<pokemon id="167">Spinarak</pokemon>
	<pokemon id="168">Ariados</pokemon>
	<pokemon id="169">Crobat</pokemon>
	<pokemon id="170">Chinchou</pokemon>
	<pokemon id="171">Lanturn</pokemon>
	<pokemon id="172">Pichu</pokemon>
	<pokemon id="173">Cleffa</pokemon>
	<pokemon id="174">Igglybuff</pokemon>
	<pokemon id="175">Togepi</pokemon>
	<pokemon id="176">Togetic</pokemon>
	<pokemon id="177">Natu</pokemon>
	<pokemon id="178">Xatu</pokemon>
	<pokemon id="179">Mareep</pokemon>
	<pokemon id="180">Flaaffy</pokemon>
	<pokemon id="181">Ampharos</pokemon>
	<pokemon id="182">Bellossom</pokemon>
	<pokemon id="183">Marill</pokemon>
	<pokemon id="184">Azumarill</pokemon>
	<pokemon id="185">Sudowoodo</pokemon>
	<pokemon id="186">Politoed</pokemon>
	<pokemon id="187">Hoppip</pokemon>
	<pokemon id="188">Skiploom</pokemon>
	<pokemon id="189">Jumpluff</pokemon>
	<pokemon id="190">Aipom</pokemon>
	<pokemon id="191">Sunkern</pokemon>
	<pokemon id="192">Sunflora</pokemon>
	<pokemon id="193">Yanma</pokemon>
	<pokemon id="194">Wooper</pokemon>
	<pokemon id="195">Quagsire</pokemon>
	<pokemon id="196">Espeon</pokemon>
	<pokemon id="197">Umbreon</pokemon>
	<pokemon id="198">Murkrow</pokemon>
	<pokemon id="199">Slowking</pokemon>
	<pokemon id="200">Misdreavus</pokemon>
	<pokemon id="201">Unown</pokemon>
	<pokemon id="202">Wobbuffet</pokemon>
	<pokemon id="203">Girafarig</pokemon>
	<pokemon id="204">Pineco</pokemon>
	<pokemon id="205">Forretress</pokemon>
	<pokemon id="206">Dunsparce</pokemon>
	<pokemon id="207">Gligar</pokemon>
	<pokemon id="208">Steelix</pokemon>
	<pokemon id="209">Snubbull</pokemon>
	<pokemon id="210">Granbull</pokemon>
	<pokemon id="211">Qwilfish</pokemon>
	<pokemon id="212">Scizor</pokemon>
	<pokemon id="213">Shuckle</pokemon>
	<pokemon id="214">Heracross</pokemon>
	<pokemon id="215">Sneasel</pokemon>
	<pokemon id="216">Teddiursa</pokemon>
	<pokemon id="217">Ursaring</pokemon>
	<pokemon id="218">Slugma</pokemon>
	<pokemon id="219">Magcargo</pokemon>
	<pokemon id="220">Swinub</pokemon>
	<pokemon id="221">Piloswine</pokemon>
	<pokemon id="222">Corsola</pokemon>
	<pokemon id="223">Remoraid</pokemon>
	<pokemon id="224">Octillery</pokemon>
	<pokemon id="225">Delibird</pokemon>
	<pokemon id="226">Mantine</pokemon>
	<pokemon id="227">Skarmory</pokemon>
	<pokemon id="228">Houndour</pokemon>
	<pokemon id="229">Houndoom</pokemon>
	<pokemon id="230">Kingdra</pokemon>
	<pokemon id="231">Phanpy</pokemon>
	<pokemon id="232">Donphan</pokemon>
	<pokemon id="233">Porygon2</pokemon>
	<pokemon id="234">Stantler</pokemon>
	<pokemon id="235">Smeargle</pokemon>
	<pokemon id="236">Tyrogue</pokemon>
	<pokemon id="237">Hitmontop</pokemon>
	<pokemon id="238">Smoochum</pokemon>
	<pokemon id="239">Elekid</pokemon>
	<pokemon id="240">Magby</pokemon>
	<pokemon id="241">Miltank</pokemon>
	<pokemon id="242">Blissey</pokemon>
	<pokemon id="243">Raikou</pokemon>
	<pokemon id="244">Entei</pokemon>
	<pokemon id="245">Suicune</pokemon>
	<pokemon id="246">Larvitar</pokemon>
	<pokemon id="247">Pupitar</pokemon>
	<pokemon id="248">Tyranitar</pokemon>
	<pokemon id="249">Lugia</pokemon>
	<pokemon id="250">Ho-Oh</pokemon>
	<pokemon id="251">Celebi</pokemon>
	<pokemon id="252">Treecko</pokemon>
	<pokemon id="253">Grovyle</pokemon>
	<pokemon id="254">Sceptile</pokemon>
	<pokemon id="255">Torchic</pokemon>
	<pokemon id="256">Combusken</pokemon>
	<pokemon id="257">Blaziken</pokemon>
	<pokemon id="258">Mudkip</pokemon>
	<pokemon id="259">Marshtomp</pokemon>
