=== Chklang/pokemonGoDB/data/lang-types.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	
	<xsd:element name="types" type="Types" />
	
	<xsd:complexType name="Types">
		<xsd:sequence>
			<xsd:element name="type" type="Type" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="Type">
		<xsd:simpleContent>
			<xsd:extension base="xsd:string">
				<xsd:attribute name="id" type="xsd:int" use="required" />
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>

</xsd:schema>

=== Chklang/pokemonGoDB/data/lang-ko/lang_types.xml
<?xml version="1.0" encoding="utf-8"?>
<types xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../lang-types.xsd">
	<type id="1">표준</type>
	<type id="2">싸움</type>
	<type id="3">비행</type>
	<type id="4">독</type>
	<type id="5">바닥</type>
	<type id="6">록</type>
	<type id="7">버그</type>
	<type id="8">유령</type>
	<type id="9">강철</type>
	<type id="10">화재</type>
	<type id="11">물</type>
	<type id="12">잔디</type>
	<type id="13">전기의</type>
	<type id="14">무당</type>
	<type id="15">얼음</type>
	<type id="16">용</type>
	<type id="17">어두운</type>
	<type id="18">요정</type>
</types>

=== Chklang/pokemonGoDB/data/lang-de/lang_types.xml
<?xml version="1.0" encoding="utf-8"?>
<types xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../lang-types.xsd">
	<type id="1">Normal</type>
	<type id="2">Kampf</type>
	<type id="3">Flug</type>
	<type id="4">Gift</type>
	<type id="5">Boden</type>
	<type id="6">Gestein</type>
	<type id="7">KÃ¤fer</type>
	<type id="8">Geist</type>
	<type id="9">Stahl</type>
	<type id="10">Feuer</type>
	<type id="11">Wasser</type>
	<type id="12">Pflanze</type>
	<type id="13">Electro</type>
	<type id="14">Psycho</type>
	<type id="15">Eis</type>
	<type id="16">Drachen</type>
	<type id="17">Unlicht</type>
	<type id="18">Fee</type>
</types>

=== Chklang/pokemonGoDB/data/types.xml
<?xml version="1.0" encoding="utf-8"?>
<types xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../lang-types.xsd">
	<type id="1">
		<type id="1">1</type>
		<type id="2">1</type>
		<type id="3">1</type>
		<type id="4">1</type>
		<type id="5">1</type>
		<type id="6">0.8</type>
		<type id="7">1</type>
		<type id="8">0.8</type>
		<type id="9">0.8</type>
		<type id="10">1</type>
		<type id="11">1</type>
		<type id="12">1</type>
		<type id="13">1</type>
		<type id="14">1</type>
		<type id="15">1</type>
		<type id="16">1</type>
		<type id="17">1</type>
		<type id="18">1</type>
	</type>
	<type id="2">
		<type id="1">1.25</type>
		<type id="2">1</type>
		<type id="3">0.8</type>
		<type id="4">0.8</type>
		<type id="5">1</type>
		<type id="6">1.25</type>
		<type id="7">0.8</type>
		<type id="8">0.8</type>
		<type id="9">1.25</type>
		<type id="10">1</type>
		<type id="11">1</type>
		<type id="12">1</type>
		<type id="13">1</type>
		<type id="14">0.8</type>
		<type id="15">1.25</type>
		<type id="16">1</type>
		<type id="17">1.25</type>
		<type id="18">0.8</type>
	</type>
	<type id="3">
		<type id="1">1</type>
		<type id="2">1.25</type>
		<type id="3">1</type>
		<type id="4">1</type>
		<type id="5">1</type>
		<type id="6">0.8</type>
		<type id="7">1.25</type>
		<type id="8">1</type>
		<type id="9">0.8</type>
		<type id="10">1</type>
		<type id="11">1</type>
		<type id="12">1.25</type>
		<type id="13">0.8</type>
		<type id="14">1</type>
		<type id="15">1</type>
		<type id="16">1</type>
		<type id="17">1</type>
		<type id="18">1</type>
	</type>
	<type id="4">
		<type id="1">1</type>
		<type id="2">1</type>
		<type id="3">1</type>
		<type id="4">0.8</type>
		<type id="5">0.8</type>
		<type id="6">0.8</type>
		<type id="7">1</type>
		<type id="8">0.8</type>
		<type id="9">0.8</type>
		<type id="10">1</type>
		<type id="11">1</type>
		<type id="12">1.25</type>
		<type id="13">1</type>
		<type id="14">1</type>
		<type id="15">1</type>
		<type id="16">1</type>
		<type id="17">1</type>
		<type id="18">1.25</type>
	</type>
	<type id="5">
		<type id="1">1</type>
		<type id="2">1</type>
		<type id="3">0.8</type>
		<type id="4">1.25</type>
		<type id="5">1</type>
		<type id="6">1.25</type>
		<type id="7">0.8</type>
		<type id="8">1</type>
		<type id="9">1.25</type>
		<type id="10">1.25</type>
		<type id="11">1</type>
		<type id="12">0.8</type>
		<type id="13">1.25</type>
		<type id="14">1</type>
		<type id="15">1</type>
		<type id="16">1</type>
		<type id="17">1</type>
		<type id="18">1</type>
	</type>
	<type id="6">
		<type id="1">1</type>
		<type id="2">0.8</type>
		<type id="3">1.25</type>
		<type id="4">1</type>
		<type id="5">0.8</type>
		<type id="6">1</type>
		<type id="7">1.25</type>
		<type id="8">1</type>
		<type id="9">0.8</type>
		<type id="10">1.25</type>
		<type id="11">1</type>
		<type id="12">1</type>
		<type id="13">1</type>
		<type id="14">1</type>
		<type id="15">1.25</type>
		<type id="16">1</type>
		<type id="17">1</type>
		<type id="18">1</type>
	</type>
	<type id="7">
		<type id="1">1</type>
		<type id="2">0.8</type>
		<type id="3">0.8</type>
		<type id="4">0.8</type>
		<type id="5">1</type>
		<type id="6">1</type>
		<type id="7">1</type>
		<type id="8">0.8</type>
		<type id="9">0.8</type>
		<type id="10">0.8</type>
		<type id="11">1</type>
		<type id="12">1.25</type>
		<type id="13">1</type>
		<type id="14">1.25</type>
		<type id="15">1</type>
		<type id="16">1</type>
		<type id="17">1.25</type>
		<type id="18">0.8</type>
	</type>
	<type id="8">
		<type id="1">0.8</type>
		<type id="2">1</type>
		<type id="3">1</type>
		<type id="4">1</type>
		<type id="5">1</type>
		<type id="6">1</type>
		<type id="7">1</type>
		<type id="8">1.25</type>
		<type id="9">1</type>
		<type id="10">1</type>
		<type id="11">1</type>
		<type id="12">1</type>
		<type id="13">1</type>
		<type id="14">1.25</type>
		<type id="15">1</type>
		<type id="16">1</type>
		<type id="17">0.8</type>
		<type id="18">1</type>
	</type>
	<type id="9">
		<type id="1">1</type>
		<type id="2">1</type>
		<type id="3">1</type>
		<type id="4">1</type>
		<type id="5">1</type>
		<type id="6">1.25</type>
		<type id="7">1</type>
		<type id="8">1</type>
		<type id="9">0.8</type>
		<type id="10">0.8</type>
		<type id="11">0.8</type>
		<type id="12">1</type>
		<type id="13">0.8</type>
		<type id="14">1</type>
		<type id="15">1.25</type>
		<type id="16">1</type>
		<type id="17">1</type>
		<type id="18">1.25</type>
	</type>
	<type id="10">
		<type id="1">1</type>
		<type id="2">1</type>
		<type id="3">1</type>
		<type id="4">1</type>
		<type id="5">1</type>
		<type id="6">0.8</type>
		<type id="7">1.25</type>
		<type id="8">1</type>
		<type id="9">1.25</type>
		<type id="10">0.8</type>
		<type id="11">0.8</type>
		<type id="12">1.25</type>
		<type id="13">1</type>
		<type id="14">1</type>
		<type id="15">1.25</type>
		<type id="16">0.8</type>
		<type id="17">1</type>
		<type id="18">1</type>
	</type>
	<type id="11">
		<type id="1">1</type>
		<type id="2">1</type>
		<type id="3">1</type>
		<type id="4">1</type>
		<type id="5">1.25</type>
		<type id="6">1.25</type>
		<type id="7">1</type>
		<type id="8">1</type>
		<type id="9">1</type>
		<type id="10">1.25</type>
		<type id="11">0.8</type>
		<type id="12">0.8</type>
		<type id="13">1</type>
		<type id="14">1</type>
		<type id="15">1</type>
		<type id="16">0.8</type>
		<type id="17">1</type>
		<type id="18">1</type>
	</type>
	<type id="12">
		<type id="1">1</type>
		<type id="2">1</type>
		<type id="3">0.8</type>
		<type id="4">0.8</type>
		<type id="5">1.25</type>
		<type id="6">1.25</type>
		<type id="7">0.8</type>
		<type id="8">1</type>
		<type id="9">0.8</type>
		<type id="10">0.8</type>
		<type id="11">1.25</type>
		<type id="12">0.8</type>
		<type id="13">1</type>
		<type id="14">1</type>
		<type id="15">1</type>
		<type id="16">0.8</type>
		<type id="17">1</type>
		<type id="18">1</type>
	</type>
	<type id="13">
		<type id="1">1</type>
		<type id="2">1</type>
		<type id="3">1.25</type>
		<type id="4">1</type>
		<type id="5">0.89</type>
		<type id="6">1</type>
		<type id="7">1</type>
		<type id="8">1</type>
		<type id="9">1</type>
		<type id="10">1</type>
		<type id="11">1.25</type>
		<type id="12">0.8</type>
		<type id="13">0.8</type>
		<type id="14">1</type>
		<type id="15">1</type>
		<type id="16">0.8</type>
		<type id="17">1</type>
		<type id="18">1</type>
	</type>
	<type id="14">
		<type id="1">1</type>
		<type id="2">1.25</type>
		<type id="3">1</type>
		<type id="4">1.25</type>
		<type id="5">1</type>
		<type id="6">1</type>
		<type id="7">1</type>
		<type id="8">1</type>
		<type id="9">0.8</type>
		<type id="10">1</type>
		<type id="11">1</type>
		<type id="12">1</type>
		<type id="13">1</type>
		<type id="14">0.8</type>
		<type id="15">1</type>
		<type id="16">1</type>
		<type id="17">0.8</type>
		<type id="18">1</type>
	</type>
	<type id="15">
		<type id="1">1</type>
		<type id="2">1</type>
		<type id="3">1.25</type>
		<type id="4">1</type>
		<type id="5">1.25</type>
		<type id="6">1</type>
		<type id="7">1</type>
		<type id="8">1</type>
		<type id="9">0.8</type>
		<type id="10">0.8</type>
		<type id="11">0.8</type>
		<type id="12">1.25</type>
		<type id="13">1</type>
		<type id="14">1</type>
		<type id="15">0.8</type>
		<type id="16">1.25</type>
		<type id="17">1</type>
		<type id="18">1</type>
	</type>
	<type id="16">
		<type id="1">1</type>
		<type id="2">1</type>
		<type id="3">1</type>
		<type id="4">1</type>
		<type id="5">1</type>
		<type id="6">1</type>
		<type id="7">1</type>
		<type id="8">1</type>
		<type id="9">0.8</type>
		<type id="10">1</type>
		<type id="11">1</type>
		<type id="12">1</type>
		<type id="13">1</type>
		<type id="14">1</type>
		<type id="15">1</type>
		<type id="16">1.25</type>
		<type id="17">1</type>
		<type id="18">0.8</type>
	</type>
	<type id="17">
		<type id="1">1</type>
		<type id="2">0.8</type>
		<type id="3">1</type>
		<type id="4">1</type>
		<type id="5">1</type>
		<type id="6">1</type>
		<type id="7">1</type>
		<type id="8">1.25</type>
		<type id="9">1</type>
		<type id="10">1</type>
		<type id="11">1</type>
		<type id="12">1</type>
		<type id="13">1</type>
		<type id="14">1.25</type>
		<type id="15">1</type>
		<type id="16">1</type>
		<type id="17">0.8</type>
		<type id="18">0.8</type>
	</type>
	<type id="18">
		<type id="1">1</type>
		<type id="2">1.25</type>
		<type id="3">1</type>
		<type id="4">0.8</type>
		<type id="5">1</type>
		<type id="6">1</type>
		<type id="7">1</type>
		<type id="8">1</type>
		<type id="9">0.8</type>
		<type id="10">0.8</type>
		<type id="11">1</type>
		<type id="12">1</type>
		<type id="13">1</type>
		<type id="14">1</type>
		<type id="15">1</type>
		<type id="16">1.25</type>
		<type id="17">1.25</type>
		<type id="18">1</type>
	</type>
</types>

=== Chklang/pokemonGoDB/data/lang-ja/types.xml
<?xml version="1.0" encoding="utf-8"?>
<types xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../lang-types.xsd">
	<type id="1">ノーマル</type>
	<type id="2">かくとう</type>
	<type id="3">ひこう</type>
	<type id="4">どく</type>
	<type id="5">じめん</type>
	<type id="6">いわ</type>
	<type id="7">むし</type>
	<type id="8">ゴースト</type>
	<type id="9">はがね</type>
	<type id="10">ほのお</type>
	<type id="11">みず</type>
	<type id="12">くさ</type>
	<type id="13">でんき</type>
	<type id="14">エスパー</type>
	<type id="15">こおり</type>
	<type id="16">ドラゴン</type>
	<type id="17">あく</type>
	<type id="18">妖精</type>
</types>

=== Chklang/pokemonGoDB/data/lang-en/lang_types.xml
<?xml version="1.0" encoding="utf-8"?>
<types xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../lang-types.xsd">
	<type id="1">Normal</type>
	<type id="2">Fighting</type>
	<type id="3">Flying</type>
	<type id="4">Poison</type>
	<type id="5">Ground</type>
	<type id="6">Rock</type>
	<type id="7">Bug</type>
	<type id="8">Ghost</type>
	<type id="9">Steel</type>
	<type id="10">Fire</type>
	<type id="11">Water</type>
	<type id="12">Grass</type>
	<type id="13">Electric</type>
	<type id="14">Psychic</type>
	<type id="15">Ice</type>
	<type id="16">Dragon</type>
	<type id="17">Dark</type>
	<type id="18">Fairy</type>
</types>

=== Chklang/pokemonGoDB/data/lang-it/types.xml
<?xml version="1.0" encoding="utf-8"?>
<types xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../lang-types.xsd">
	<type id="1">Normale</type>
	<type id="2">Lotta</type>
	<type id="3">Volante</type>
	<type id="4">Veleno</type>
	<type id="5">Terra</type>
	<type id="6">Roccia</type>
	<type id="7">Coleottero</type>
	<type id="8">Spettro</type>
	<type id="9">Acciaio</type>
	<type id="10">Fuoco</type>
	<type id="11">Acqua</type>
	<type id="12">Erba</type>
	<type id="13">Elettro</type>
	<type id="14">Psico</type>
	<type id="15">Ghiaccio</type>
	<type id="16">Drago</type>
	<type id="17">Buio</type>
	<type id="18">Fata</type>
</types>
