=== Chklang/pokemonGoDB/data/lang-attacks.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	
	<xsd:element name="attacks" type="Attacks" />
	
	<xsd:complexType name="Attacks">
		<xsd:sequence>
			<xsd:element name="attack" type="Attack" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="Attack">
		<xsd:simpleContent>
			<xsd:extension base="xsd:string">
				<xsd:attribute name="id" type="xsd:int" use="required" />
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>

</xsd:schema>

=== Chklang/pokemonGoDB/data/lang-ko/attacks.xml
<?xml version="1.0" encoding="utf-8"?>
<attacks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="lang-attacks.xsd">
	<attack id="1">김밥말이 (Gimbapmal\'i)</attack>
	<attack id="2">파괴광선 (Pagoe Gwangseon)</attack>
	<attack id="3">악의파동 (Ak-yi Padong)</attack>
	<attack id="4">오물공격 (Omul Gonggyeok)</attack>
	<attack id="5">찝기 (Jjipgi)</attack>
	<attack id="6">화염자동차 (Hwayeom Jadongcha)</attack>
	<attack id="7">메가폰 (Megapon)</attack>
	<attack id="8">화염방사 (Hwayeom Bangsa)</attack>
	<attack id="9">구멍파기 (Gumeong Pagi)</attack>
	<attack id="10">크로스촙 (Cross Chop)</attack>
	<attack id="11">환상빔 (Hwansang Beam)</attack>
	<attack id="12">지진 (Jijin)</attack>
	<attack id="13">스톤에지 (Stone Edge)</attack>
	<attack id="14">냉동펀치 (Naengdong Punch)</attack>
	<attack id="15">하트스탬프 (Heart Stamp)</attack>
	<attack id="16">방전 (Bangjeon)</attack>
	<attack id="17">러스터캐논 (Luster Cannon)</attack>
	<attack id="18">회전부리 (Hoejeon Buri)</attack>
	<attack id="19">냉동빔 (Naengdong Beam)</attack>
	<attack id="20">눈보라 (Nunbora)</attack>
	<attack id="21">열풍 (Yeolpung)</attack>
	<attack id="22">제비반환 (Jebi Banhwan)</attack>
	<attack id="23">드릴라이너 (Drill Liner)</attack>
	<attack id="24">꽃보라 (Kkotbora)</attack>
	<attack id="25">메가드레인 (Mega Drain)</attack>
	<attack id="26">벌레의야단법석 (Beolle-yi Yadanbeopseok)</attack>
	<attack id="27">독엄니 (Dok Eomni)</attack>
	<attack id="28">깜짝베기 (Kkamjjakbegi)</attack>
	<attack id="29">거품광선 (Geopum Gwangseon)</attack>
	<attack id="30">지옥의바퀴 (Jiok-yi Bakwi)</attack>
	<attack id="31">로킥 (Low Kick)</attack>
	<attack id="32">아쿠아제트 (Aqua Jet)</attack>
	<attack id="33">아쿠아테일 (Aqua Tail)</attack>
	<attack id="34">씨폭탄 (Ssi Poktan)</attack>
	<attack id="35">사이코쇼크 (Psycho Shock)</attack>
	<attack id="36">원시의힘 (Weonsa-yi Him)</attack>
	<attack id="37">암석봉인 (Amseok Bong\'in)</attack>
	<attack id="38">스톤샤워 (Stone Shower)</attack>
	<attack id="39">파워젬 (Power Gem)</attack>
	<attack id="40">야습 (Yaseup)</attack>
	<attack id="41">섀도펀치 (Shadow Punch)</attack>
	<attack id="42">괴상한바람 (Goesanghan Baram)</attack>
	<attack id="43">섀도볼 (Shadow Ball)</attack>
	<attack id="44">마그넷봄 (Magnet Bomb)</attack>
	<attack id="45">아이언헤드 (Iron Head)</attack>
	<attack id="46">파라볼라차지 (Parabola Charge)</attack>
	<attack id="47">번개펀치 (Beongae Punch)</attack>
	<attack id="48">번개 (Beongae)</attack>
	<attack id="49">１０만볼트 (Sipman Volt)</attack>
	<attack id="50">회오리 (Hoe\'ori)</attack>
	<attack id="51">용의파동 (Yong-yi Padong)</attack>
	<attack id="52">드래곤크루 (Dragon Claw)</attack>
	<attack id="53">차밍보이스 (Charming Voice)</attack>
	<attack id="54">드게인키스 (Drain Kiss)</attack>
	<attack id="55">매지컬샤인 (Magical Shine)</attack>
	<attack id="56">문포스 (Moon Force)</attack>
	<attack id="57">치근거리기 (Chigeungeorigi)</attack>
	<attack id="58">크로스포이즌 (Cross Poison)</attack>
	<attack id="59">오물폭탄 (Omul Poktan)</attack>
	<attack id="60">오물웨이브 (Omul Wave)</attack>
	<attack id="61">더스트슈트 (Dust Shoot)</attack>
	<attack id="62">뼈다귀치기 (Ppyeo Dagwichigi)</attack>
	<attack id="63">땅고르기 (Thang Gorugi)</attack>
	<attack id="64">진흙폭탄 (Jinheulk Poktan)</attack>
	<attack id="65">시그널빔 (Signal Beam)</attack>
	<attack id="66">시저크로스 (Scissor Cross)</attack>
	<attack id="67">니트로차지 (Nitro Charge)</attack>
	<attack id="68">불꽃튀기기 (Bulkot Twigigi)</attack>
	<attack id="69">불대문자 (Bul Daemunja)</attack>
	<attack id="70">소금물 (Sogeummul)</attack>
	<attack id="71">물의파동 (Mul-yi Padong)</attack>
	<attack id="72">열탕 (Yultang)</attack>
	<attack id="73">하이드로펌프 (Hydro Pump)</attack>
	<attack id="74">사이코키네시스 (Psychokinesis)</attack>
	<attack id="75">사이코브레이크 (Psycho Break)</attack>
	<attack id="76">얼다바람 (Eolda Baram)</attack>
	<attack id="77">기가드레인 (Giga Drain)</attack>
	<attack id="78">불꽃펀치 (Bulkkot Punch)</attack>
	<attack id="79">솔라빔 (Solar Beam)</attack>
	<attack id="80">리프블레이드 (Leaf Blade)</attack>
	<attack id="81">파워휩 (Power Whip)</attack>
	<attack id="82">에어컷터 (Air Cutter)</attack>
	<attack id="83">폭풍 (Pohkpoong)</attack>
	<attack id="84">깨트리다 (Kkaeteurida)</attack>
	<attack id="85">스피드스타 (Speed Star)</attack>
	<attack id="86">뿔찌르기 (Ppul Jjireugi)</attack>
	<attack id="87">짓밟기 (Jitbalgi)</attack>
	<attack id="88">필살앞니 (Pilsal Apni)</attack>
	<attack id="89">누르기 (Nureugi)</attack>
	<attack id="90">잠자기 (Jamjagi)</attack>
	<attack id="91">발버둥 (Balbeodung)</attack>
	<attack id="92">연속자르기 (Yeonsok Jareugi)</attack>
	<attack id="93">벌레먹음 (Beolle Meok\'eum)</attack>
	<attack id="94">물기 (Mulgi)</attack>
	<attack id="95">기습 (Giseup)</attack>
	<attack id="96">용의숨결 (Yong-yi Sumgyeol)</attack>
	<attack id="97">전기쇼크 (Jeongi Shock)</attack>
	<attack id="98">스파크 (Spark)</attack>
	<attack id="99">잡치기 (Japchigi)</attack>
	<attack id="100">태권당수 (Taegweon Dangsu)</attack>
	<attack id="101">불꽃세례 (Bulkkot Serye)</attack>
	<attack id="102">날개치기 (Nalgae Chigi)</attack>
	<attack id="103">쪼기 (Jjogi)</attack>
	<attack id="104">핥기 (Hatgi)</attack>
	<attack id="105">섀도크루 (Shadow Claw)</attack>
	<attack id="106">덩굴채찍 (Deonggul Chaejjik)</attack>
	<attack id="107">잎날가르기 (Ipnal Gareugi)</attack>
	<attack id="108">머드숏 (Mud Shot)</attack>
	<attack id="109">얼음뭉치 (Eol\'eum Mungchi)</attack>
	<attack id="110">얼음숨결 (Eureum Soomgyul)</attack>
	<attack id="111">전광석화 (Jeongwang Seokhwa)</attack>
	<attack id="112">할퀴기 (Halkwigi)</attack>
	<attack id="113">몸통박치기 (Momtong Bakchigi)</attack>
	<attack id="114">막치기 (Makchigi)</attack>
	<attack id="115">풀베기 (Pul Begi)</attack>
	<attack id="116">독찌르기 (Dok Jjareugi)</attack>
	<attack id="117">용해액 (Yonghae Aek)</attack>
	<attack id="118">사이코커터 (Psycho Cutter)</attack>
	<attack id="119">돌떨구기 (Dol Tteolgugi)</attack>
	<attack id="120">메탈크로우 (Metal Claw)</attack>
	<attack id="121">불릿펀치 (Bullet Punch)</attack>
	<attack id="122">물대포 (Mul Daepo)</attack>
	<attack id="123">튀어오르기 (Twieo Oreugi)</attack>
	<attack id="124">진흙뿌리기 (Jinheuk Ppurigi)</attack>
	<attack id="125">사념의박치기 (Sanyeom-yi Bakchigi)</attack>
	<attack id="126">염동력 (Yeomdongryeok)</attack>
	<attack id="127">독침 (Dokchim)</attack>
	<attack id="128">거품 (Geopum)</attack>
	<attack id="129">속여때리기 (Sok\'yeo Ttaerigi)</attack>
	<attack id="130">강철날개 (Gangcheol Nalgae)</attack>
	<attack id="131">불꽃엄니 (Bulkkot Eomni)</attack>
	<attack id="132">바위깨기 (Bawi Kkaegi)</attack>
</attacks>

=== Chklang/pokemonGoDB/data/lang-en/attacks.xml
<?xml version="1.0" encoding="utf-8"?>
<attacks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../lang-attacks.xsd">
	<attack id="1">Wrap</attack>
	<attack id="2">Hyper Beam</attack>
	<attack id="3">Dark Pulse</attack>
	<attack id="4">Sludge</attack>
	<attack id="5">Vice Grip</attack>
	<attack id="6">Flame Wheel</attack>
	<attack id="7">Megahorn</attack>
	<attack id="8">Flamethrower</attack>
	<attack id="9">Dig</attack>
	<attack id="10">Cross Chop</attack>
	<attack id="11">Psybeam</attack>
	<attack id="12">Earthquake</attack>
	<attack id="13">Stone Edge</attack>
	<attack id="14">Ice Punch</attack>
	<attack id="15">Heart Stamp</attack>
	<attack id="16">Discharge</attack>
	<attack id="17">Flash Cannon</attack>
	<attack id="18">Drill Peck</attack>
	<attack id="19">Ice Beam</attack>
	<attack id="20">Blizzard</attack>
	<attack id="21">Heat Wave</attack>
	<attack id="22">Aerial Ace</attack>
	<attack id="23">Drill Run</attack>
	<attack id="24">Petal Blizzard</attack>
	<attack id="25">Mega Drain</attack>
	<attack id="26">Bug Buzz</attack>
	<attack id="27">Poison Fang</attack>
	<attack id="28">Night Slash</attack>
	<attack id="29">Bubble Beam</attack>
	<attack id="30">Submission</attack>
	<attack id="31">Low Sweep</attack>
	<attack id="32">Aqua Jet</attack>
	<attack id="33">Aqua Tail</attack>
	<attack id="34">Seed Bomb</attack>
	<attack id="35">Psyshock</attack>
	<attack id="36">Ancient Power</attack>
	<attack id="37">Rock Tomb</attack>
	<attack id="38">Rock Slide</attack>
	<attack id="39">Power Gem</attack>
	<attack id="40">Shadow Sneak</attack>
	<attack id="41">Shadow Punch</attack>
	<attack id="42">Ominous Wind</attack>
	<attack id="43">Shadow Ball</attack>
	<attack id="44">Magnet Bomb</attack>
	<attack id="45">Iron Head</attack>
	<attack id="46">Parabolic Charge</attack>
	<attack id="47">Thunder Punch</attack>
	<attack id="48">Thunder</attack>
	<attack id="49">Thunderbolt</attack>
	<attack id="50">Twister</attack>
	<attack id="51">Dragon Pulse</attack>
	<attack id="52">Dragon Claw</attack>
	<attack id="53">Disarming Voice</attack>
	<attack id="54">Draining Kiss</attack>
	<attack id="55">Dazzling Gleam</attack>
	<attack id="56">Moonblast</attack>
	<attack id="57">Play Rough</attack>
	<attack id="58">Cross Poison</attack>
	<attack id="59">Sludge Bomb</attack>
	<attack id="60">Sludge Wave</attack>
	<attack id="61">Gunk Shot</attack>
	<attack id="62">Bone Club</attack>
	<attack id="63">Bulldoze</attack>
	<attack id="64">Mud Bomb</attack>
	<attack id="65">Signal Beam</attack>
	<attack id="66">X-Scissor</attack>
	<attack id="67">Flame Charge</attack>
	<attack id="68">Flame Burst</attack>
	<attack id="69">Fire Blast</attack>
	<attack id="70">Brine</attack>
	<attack id="71">Water Pulse</attack>
	<attack id="72">Scald</attack>
	<attack id="73">Hydro Pump</attack>
	<attack id="74">Psychic</attack>
	<attack id="75">Psystrike</attack>
	<attack id="76">Icy Wind</attack>
	<attack id="77">Giga Drain</attack>
	<attack id="78">Fire Punch</attack>
	<attack id="79">Solar Beam</attack>
	<attack id="80">Leaf Blade</attack>
	<attack id="81">Power Whip</attack>
	<attack id="82">Air Cutter</attack>
	<attack id="83">Hurricane</attack>
	<attack id="84">Brick Break</attack>
	<attack id="85">Swift</attack>
	<attack id="86">Horn Attack</attack>
	<attack id="87">Stomp</attack>
	<attack id="88">Hyper Fang</attack>
	<attack id="89">Body Slam</attack>
	<attack id="90">Rest</attack>
	<attack id="91">Struggle</attack>
	<attack id="92">Fury Cutter</attack>
	<attack id="93">Bug Bite</attack>
	<attack id="94">Bite</attack>
	<attack id="95">Sucker Punch</attack>
	<attack id="96">Dragon Breath</attack>
	<attack id="97">Thunder Shock</attack>
	<attack id="98">Spark</attack>
	<attack id="99">Low Kick</attack>
	<attack id="100">Karate Chop</attack>
	<attack id="101">Ember</attack>
	<attack id="102">Wing Attack</attack>
	<attack id="103">Peck</attack>
	<attack id="104">Lick</attack>
	<attack id="105">Shadow Claw</attack>
	<attack id="106">Vine Whip</attack>
	<attack id="107">Razor Leaf</attack>
	<attack id="108">Mud Shot</attack>
	<attack id="109">Ice Shard</attack>
	<attack id="110">Frost Breath</attack>
	<attack id="111">Quick Attack</attack>
	<attack id="112">Scratch</attack>
	<attack id="113">Tackle</attack>
	<attack id="114">Pound</attack>
	<attack id="115">Cut</attack>
	<attack id="116">Poison Jab</attack>
	<attack id="117">Acid</attack>
	<attack id="118">Psycho Cut</attack>
	<attack id="119">Rock Throw</attack>
	<attack id="120">Metal Claw</attack>
	<attack id="121">Bullet Punch</attack>
	<attack id="122">Water Gun</attack>
	<attack id="123">Splash</attack>
	<attack id="124">Mud-Slap</attack>
	<attack id="125">Zen Headbutt</attack>
	<attack id="126">Confusion</attack>
	<attack id="127">Poison Sting</attack>
	<attack id="128">Bubble</attack>
	<attack id="129">Feint Attack</attack>
	<attack id="130">Steel Wing</attack>
	<attack id="131">Fire Fang</attack>
	<attack id="132">Rock Smash</attack>
</attacks>
